<?php

namespace WordBundle\Repository;

/**
 * FastnoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FastnoticeRepository extends \Doctrine\ORM\EntityRepository
{
}
