services:
#    talk.example:
#        class: TalkBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  espeak.text.file:
    class: TalkBundle\Espeak\EspeakTextFile
    arguments: ["@service_container"]

  espeak.mp3:
      class: TalkBundle\Espeak\EspeakMp3
      arguments: ["@service_container"]

  espeak.manager:
      class: TalkBundle\Espeak\EspeakManager
      arguments: ["@espeak.text.file", "@espeak.mp3"]
